### ISSUE TITLE
Problem mit Lehrer-Tabelle

### ISSUE THREAD

**Issue by RED-Pixl** [Quantum066/erasmus_vorbereitung#1]
Wenn man das Python-File ausführt kommt immer folgender Fehler:

```
Traceback (most recent call last):
  File "C:\Users\User\OneDrive\Documents\Coding Projects\PyCharm\erasmus_vorbereitung\Stundenplan\main.py", line 34, in <module>
    cursor.execute("""
sqlite3.OperationalError: near "auto_increment": syntax error
```

da scheint wohl was mit dem Script für die DB nicht zu stimmen

**Comment by K-Andrei-P** [comment]
Das problem ist, dass hier den falschen Script benutzt wurde. Hier hast du den VertretungsplanDBScript datei benutzt. Zu nutzen war eigentlich den .sql Datei und das ganze hätte glaub ich mit einem execute fertig sein können. Mein fehler, hab halt den VertretungsplanDBScript drinnen gelassen, weil es da übersichtilicher war. 

Wenn du es nicht nochmal ändern möchtest und das Problem hier nur lösen möchtest, ist der Fehler ein syntax Fehler bei den Foreign Keys. Syntax ist: 'foreign key "key" references "key"

**Comment by K-Andrei-P** [comment]
Wenn eigentlich alles funktioniert hat selbst mit den Syntax Fehler ist das andere Problem leider nicht mit den executes lösbar. AUTO_INCREMENT gibt automatisch neue Objekte in der klasse eine Zahl hier: ID. Wenn das nicht via python lösbar ist weiß ich leider nicht mehr.
